name: YayDungeons
version: '${project.version}'
main: yaya.dungeons.YayDungeons
api-version: 1.18
authors: [ Absolutelyaya ]
website: https://www.curseforge.com/members/absolutelyaya/projects
depend: [ WorldEdit ]
commands:
  dungen:
    description: Debug command for generating a new dungeon
  leave:
    description: Leave a dungeon
  dungeons:
    description: description
#permissions:
