name: YayDungeons
version: versyon
main: yaya.dungeons.YayDungeons
api-version: 1.18
authors: [ Absolutelyaya ]
website: https://www.curseforge.com/members/absolutelyaya/projects
depend: [ WorldEdit ]
commands:
  dungen:
    description: Debug command for generating a new dungeon
  leave:
    description: Leave a dungeon
  dungeons:
    description: Open the Dungeon Browser
  dungeonmods:
    description: Check the Mods of the Dungeon that you're in
  dungeonaccept:
    description: accept a Dungeon join request or invite
  dungeondecline:
    description: decline a Dungeon join request or invite
#permissions: